// Get Backing Constants
export const GET_BACKINGS_PENDING = "GET_BACKINGS_PENDING";
export const GET_BACKINGS_SUCCESS = "GET_BACKINGS_SUCCESS";
export const GET_BACKINGS_FAILED = "GET_BACKINGS_FAILED";
// Add Backing Constants
export const ADD_BACKING_PENDING = "ADD_BACKING_PENDING";
export const ADD_BACKING_SUCCESS = "ADD_BACKING_SUCCESS";
export const ADD_BACKING_FAILED = "ADD_BACKING_FAILED";
// Remove Backing Constants
export const REMOVE_BACKING_PENDING = "REMOVE_BACKING_PENDING";
export const REMOVE_BACKING_SUCCESS = "REMOVE_BACKING_SUCCESS";
export const REMOVE_BACKING_FAILED = "REMOVE_BACKING_FAILED";
// Update Backing Constants
export const UPDATE_BACKING_PENDING = "UPDATE_BACKING_PENDING";
export const UPDATE_BACKING_SUCCESS = "UPDATE_BACKING_SUCCESS";
export const UPDATE_BACKING_FAILED = "UPDATE_BACKING_FAILED";
