// Get Rearend Constants
export const GET_REARENDS_PENDING = "GET_REARENDS_PENDING";
export const GET_REARENDS_SUCCESS = "GET_REARENDS_SUCCESS";
export const GET_REARENDS_FAILED = "GET_REARENDS_FAILED";
// Add Rearend Constants
export const ADD_REAREND_PENDING = "ADD_REAREND_PENDING";
export const ADD_REAREND_SUCCESS = "ADD_REAREND_SUCCESS";
export const ADD_REAREND_FAILED = "ADD_REAREND_FAILED";
// Remove REAREND Constants
export const REMOVE_REAREND_PENDING = "REMOVE_REAREND_PENDING";
export const REMOVE_REAREND_SUCCESS = "REMOVE_REAREND_SUCCESS";
export const REMOVE_REAREND_FAILED = "REMOVE_REAREND_FAILED";
// Update REAREND Constants
export const UPDATE_REAREND_PENDING = "UPDATE_REAREND_PENDING";
export const UPDATE_REAREND_SUCCESS = "UPDATE_REAREND_SUCCESS";
export const UPDATE_REAREND_FAILED = "UPDATE_REAREND_FAILED";
